[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.devnet]
ore_delegation = "DeoREdoVi3iqMHQq6sFHD2gBQUYQUMoBEEf3WqpQwLu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../ore_mining/deore-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
